name: Build and upload assets and index

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - uses: actions/upload-artifact@v1
      with:
        name: build-${{github.sha}}
        path: build/

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build from previous step
      uses: actions/download-artifact@v1
      with:
        name: build-${{github.sha}}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
    - name: Upload assets to assets-bucket using the AWS cli
      run: >-
        aws s3 cp build-${{github.sha}} s3://tf-assets-thea/assets/${{github.sha}}/ --recursive --acl public-read --cache-control public,max-age=31536000,immutable
    - name: Create index html
      run: >-
        cd src-index; sh index.sh
    - name: Upload index.html
      run: >-
        aws s3 cp index.html s3://tf-host-thea/index.html --cache-controle no-store --acl public-read
